version: "3.7"

services: 
  database_chargeit:
    image: postgres
    container_name: database_chargeit
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=it123
      - POSTGRES_DB=chargeit_database
    volumes:
      - pgdata:/data/postgres
  chargeit_backend: 
    build: .
    container_name: chargeit_backend
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_chargeit
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database_chargeit
      - DATABASE_USER=docker
      - DATABASE_PASS=it123
      - DATABASE_PORT=5432
      - DATABASE_NAME=chargeit_database

volumes:
  pgdata:
    driver: local
